_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.18.7
            "6": 4.49.0.dev0
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
epochs:
    value: 40
learning_rate:
    value: 0.001
mode:
    value: scratch
